name: second_sight
description: A Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.8.5
  camera: ^0.10.5+5
  google_mlkit_object_detection: ^0.12.0
  google_mlkit_pose_detection: ^0.12.0
  sensors_plus: ^4.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.3
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
